# Generated by Django 5.2.8 on 2025-11-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер уровня')),
                ('title', models.CharField(max_length=200, verbose_name='Название уровня')),
                ('theory_text', models.TextField(verbose_name='Теоретический материал')),
                ('skills', models.TextField(verbose_name='Навыки после уровня')),
                ('materials', models.TextField(verbose_name='Материалы уровня')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название минерала')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='minerals/', verbose_name='Изображение')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('streak', models.CharField(max_length=100, verbose_name='Цвет черты')),
                ('luster', models.CharField(choices=[('metallic', 'Металлический'), ('glassy', 'Стеклянный'), ('pearly', 'Перламутровый'), ('greasy', 'Жирный'), ('dull', 'Тусклый')], max_length=20, verbose_name='Блеск')),
                ('crystal_system', models.CharField(choices=[('cubic', 'Кубическая'), ('tetragonal', 'Тетрагональная'), ('hexagonal', 'Гексагональная'), ('orthorhombic', 'Ромбическая'), ('monoclinic', 'Моноклинная'), ('triclinic', 'Триклинная')], max_length=20, verbose_name='Кристаллическая система')),
                ('cleavage', models.CharField(max_length=100, verbose_name='Спайность')),
                ('fracture', models.CharField(max_length=100, verbose_name='Излом')),
                ('hardness', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Твердость по Моосу')),
                ('density', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Плотность')),
                ('reaction_with_acid', models.BooleanField(default=False, verbose_name='Реакция с HCl')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Минерал',
                'verbose_name_plural': 'Минералы',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level', verbose_name='Уровень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'level')},
            },
        ),
    ]
